###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "push up",
    "reps": 25,
    "weight": 165,
    "unit": "lbs",
    "date": "12/05/21"
}

###
GET http://localhost:3000/exercises HTTP/1.1

###
GET http://localhost:3000/exercises/61ad7054bce90c7ae6644778 HTTP/1.1

###

PUT http://localhost:3000/exercises/61ad7054bce90c7ae6644778 HTTP/1.1
content-type: application/json

{
    "name": "push up",
    "reps": 35,
    "weight": 165,
    "unit": "LBs",
    "date": "12/15/21"
}

###
DELETE http://localhost:3000/exercises/61ad796da84f3373e22b782f HTTP/1.1


###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "title": "Eternal Sunshine Of The Spotless Mind",
    "year": 2004,
    "language": "English"
}

###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "title": "High Fidelity",
    "year": 2000,
    "language": "English"
}

###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "title": "Anchorman",
    "year": 2004,
    "language": "English"
}


###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "title": "No Country For Old Men",
    "year": 2007,
    "language": "English"
}


###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "title": "A Serious Man",
    "year": 2009,
    "language": "English"
}


###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "title": "City Of God",
    "year": 2003,
    "language": "Portuguese"
}

###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "title": "Parasite",
    "year": 2019,
    "language": "Korean"
}
